### ISSUE TITLE
[feature] Read invoice QR code on mobile

### ISSUE THREAD

**Issue by andrerfneves** [andrerfneves/lightning-decoder#1]
## User Story
As a user, on any mobile device, when I open https://lightningdecoder.com, I should see a button similar to the right arrow button, but with a Camera icon. As a user I'm able to press that button and have the ability to scan a QR code by using the phone's camera. It should read the QR code and input and seamlessly show the user the results container (or error message).

Use any camera icon SVG or PNG. No need for a full on font-family/package for icons.

## Possible Libs
I only found this doing a little bit of research. Could be better alternatives of course.
https://github.com/schmich/instascan

## Screenshots
<img width="412" alt="screen shot 2019-01-02 at 8 13 06 pm" src="https://user-images.githubusercontent.com/2574011/50620422-18e11700-0ecd-11e9-96d7-a8a8f7727c7a.png">

## Tasks
- [x] Introduce support for browser camera
- [x] Add QR code camera reading capabilities
- [x] Responsive styles to ensure usability and accessibility

**Comment by andrerfneves** [comment]
Resolved
