### ISSUE TITLE
[bug] Fix styles on mobile error messages

### ISSUE THREAD

**Issue by andrerfneves** [andrerfneves/lightning-decoder#6]
## User Story
As a user, on any mobile device, when I open https://lightningdecoder.com, and try to submit a lightning invoice, and it errors out, I should see the error message. Right now the styles are not applied for mobile screens.

## Screenshots
<img width="571" alt="screen shot 2019-01-02 at 8 12 57 pm" src="https://user-images.githubusercontent.com/2574011/50620120-bb989600-0ecb-11e9-9496-1f7917347d23.png">

## Tasks
- [x] On mobile, the error message should come after the Submit button (arrow)
- [x] Responsive styles to ensure usability and accessibility
- [x] Widest that the error container should go is the same width as the input above.

**Comment by andrerfneves** [comment]
Resolved
