### ISSUE TITLE
[bug] Fix styles on mobile success container

### ISSUE THREAD

**Issue by andrerfneves** [andrerfneves/lightning-decoder#7]
## User Story
As a user, on any mobile device, when I open https://lightningdecoder.com, and try to submit a lightning invoice, and it succeeds, I should see the correct layout for success message/container.

## Screenshots
<img width="583" alt="screen shot 2019-01-02 at 8 22 41 pm" src="https://user-images.githubusercontent.com/2574011/50620269-6dd05d80-0ecc-11e9-96b5-c308177143aa.png">

## Tasks
- [x] When the success container is shown, hide the absolutely positioned GitHub and Bitcoin icons from the bottom of the view  (check screenshot)
- [x] When the success container is show, it should be moved down BELOW the X (cancel) button it is currently covering it (check screenshot)
- [x] Ensure responsiveness (widest the success container should go is as wide as the input above it)
- [x] Ensure that the user is able to scroll on the page to read all of the information (vertically, as well as horizontally -- inside the container).

## Lightning Invoice for testing
lnbc20m1pvjluezhp58yjmdan79s6qqdhdzgynm4zwqd5d7xmw5fk98klysy043l2ahrqspp5qqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqypqfppqw508d6qejxtdg4y5r3zarvary0c5xw7kepvrhrm9s57hejg0p662ur5j5cr03890fa7k2pypgttmh4897d3raaq85a293e9jpuqwl0rnfuwzam7yr8e690nd2ypcq9hlkdwdvycqa0qza8

**Comment by andrerfneves** [comment]
Resolved
